title = "AF.Umbraco.Azure.Blob.Media.Storage Gitleaks Config"

[extend]
useDefault = true

[[allowlists]]
description = "Ignore generated and build artifacts"
paths = [
  '''^src/.*/bin/''',
  '''^src/.*/obj/''',
  '''^msbuild\.log$''',
  '''^msbuild\.binlog$'''
]
